### ISSUE TITLE
Client-side load balancer with service discovery

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye#52]
# Client Side Load Balancer with Service Discovery project proposal

## Motivation
The project should address the following use cases.

#### Kubernetes Service Discovery
Similar to [Spring Discovery Client](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/index.html#discoveryclient-for-kubernetes) we should provide a way to get service URL by service name.
In this case, the library would act as Service Discovery only

#### Zookeeper, Consul and others
The goal is to provide an extensible solution so that it is easy to add support for common service discovery servers. 

### Load balancer
Even if our main target environment is Kubernetes, users of our software often integrate their services with systems not running on Kubernetes, often legacy systems.
Furthermore, for some protocols, like gRPC, the built-in kubernetes load balancing is not optimal, see https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/
We could address this in this new project, eliminating the need of using an additional proxy to load balance the calls.

## Other solutions
OpenFeign - focused on rest/http calls, integrated with spring but only for blocking calls, PR history shows there is some support for non-blocking now too, **does not support** grpc

Netflix stack - in the maintenance mode

Provider-specific solutions: [Kumuluzee Discovery](https://github.com/kumuluz/kumuluzee-discovery), [Spring Cloud Load Balancer](https://spring.io/blog/2020/03/25/spring-tips-spring-cloud-loadbalancer)

## Current plan
We plan to create a customizable load balancer with service discovery.
The initial plan was to create something in Quarkus that we could use for gRPC and rest-clients but we think that it would be better to have it in SmallRye so that other projects, like e.g. RestEasy can easily integrate with it.

We want it configured with MicroProfile Config, with customizable Service Discovery part (or AddressListProvider, as it's called in the code now), and customizable Load Balancer. One of the intents is also to have it abstracted from the protocol used underneath.

Some early beginnings of the works: https://github.com/michalszynkiewicz/smallrye-load-balancer

Further plans include smart load-balancing, based on the response times, failure rates, etc.

**Comment by kenfinnigan** [comment]
Was there any evaluation of existing open-source projects with similar functionality?

**Comment by kenfinnigan** [comment]
Is it possible to have some use-cases of what this solves that aren't handled with alternatives, such as DNS in Kubernetes?

**Comment by michalszynkiewicz** [comment]
That's a good question. 
I have looked at some other projects to see how they do the job but haven't looked for a project that could be used instead of us implementing something. I/we will take a look around.

**Comment by cescoffier** [comment]
There are several use cases:

1. Not everybody is on Kubernetes - we had many requests for Consul, Eureka, and other discovery mechanisms.
2. DNS does not fit a highly dynamic environment where events happen more often than the TTL of the records
3. Not everything you need to discover is a DNS address, imagine discovering a Kafka topic for instance. Defining your own TXT record is complicated, and generally error-prone (String parsing). It also not great at looking for services by metadata.
4. Client-side load balancing allows a more sophisticated load-balancing strategy than Kube, typically it's where you would introduce Istio (but Kubernetes is not everywhere, and Kubernetes + a service mesh is not the norm yet). Stats based load-balancing is much more appropriate in hybrid cloud deployments where the latency between instances can be very different. 
5. This component is required for gRPC which defines service discovery and load balancing as core features. We can't support them at the moment because of the lack of such a component. 

There are no open-source projects proposing a reusable, unopinionated approach for these. There are plenty of services discovery infrastructure, but the SPI to introduce them are specifics (Feign, Kumuluzee, even gRPC has its own).

**Comment by cescoffier** [comment]
A few articles about gRPC:

- https://grpc.io/blog/grpc-load-balancing/
- https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/xds/v3/discovery.proto (just to give an idea, this is not really specified)
- https://github.com/grpc/grpc/blob/master/doc/load-balancing.md

**Comment by cescoffier** [comment]
Closing that issue - Stork is flying 🤣
